const { withDangerousMod, withXcodeProject } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Keeps Xcode archive output clean. Everything under ios/ is regenerated by
// `expo prebuild`, so all of this must be applied here, not by hand:
// 1. Podfile post_install patch — third-party Pods (Reanimated, RNScreens,
//    safe-area-context, ReactCodegen, ...) ship warnings we can't fix
//    upstream. Warnings stay fully ON for the app target itself.
// 2. LastUpgradeCheck pinned high — silences "Update to recommended settings".

const PODFILE_MARKER = 'withCleanXcodeBuild';

const PODFILE_HOOK = `    # ${PODFILE_MARKER}: silence third-party Pod build noise (app target keeps warnings).
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |bc|
        bc.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        bc.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
        # libtool "has no symbols" notes from platform-conditional codegen files
        bc.build_settings['OTHER_LIBTOOLFLAGS'] = '-no_warning_for_no_symbols'
        # linker notes such as "-undefined dynamic_lookup is deprecated on iOS"
        bc.build_settings['OTHER_LDFLAGS'] = ['$(inherited)', '-Xlinker', '-w']
      end
      # hermes-engine's replace-config script phase declares no outputs, which
      # makes Xcode warn it "will be run during every build" — acknowledge it.
      t.shell_script_build_phases.each do |phase|
        no_outputs = (phase.output_paths.nil? || phase.output_paths.empty?) &&
                     (phase.output_file_list_paths.nil? || phase.output_file_list_paths.empty?)
        phase.always_out_of_date = '1' if no_outputs
      end
    end
`;

function withQuietPods(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      let podfile = fs.readFileSync(podfilePath, 'utf8');
      if (!podfile.includes(PODFILE_MARKER)) {
        podfile = podfile.replace(
          /(post_install do \|installer\|\n)/,
          `$1${PODFILE_HOOK}`
        );
        fs.writeFileSync(podfilePath, podfile);
      }

      // Shared scheme carries its own LastUpgradeVersion nag.
      const iosRoot = config.modRequest.platformProjectRoot;
      const schemes = fs
        .readdirSync(iosRoot)
        .filter((d) => d.endsWith('.xcodeproj'))
        .map((d) => path.join(iosRoot, d, 'xcshareddata', 'xcschemes'))
        .filter((d) => fs.existsSync(d))
        .flatMap((d) =>
          fs.readdirSync(d).filter((f) => f.endsWith('.xcscheme')).map((f) => path.join(d, f))
        );
      for (const scheme of schemes) {
        const contents = fs.readFileSync(scheme, 'utf8');
        const patched = contents.replace(/LastUpgradeVersion = "\d+"/, 'LastUpgradeVersion = "9999"');
        if (patched !== contents) fs.writeFileSync(scheme, patched);
      }

      // Route the bundle phase's hermesc through a -w wrapper so the
      // main.jsbundle "variable X was not declared" notes stop appearing.
      // react-native-xcode.sh only sets HERMES_CLI_PATH when it's empty.
      const xcodeEnvPath = path.join(iosRoot, '.xcode.env');
      const exportLine =
        '\n# withCleanXcodeBuild: silence hermesc bytecode-compile warnings\n' +
        'export HERMES_CLI_PATH="$PROJECT_DIR/../scripts/hermesc-quiet.sh"\n';
      let xcodeEnv = fs.existsSync(xcodeEnvPath) ? fs.readFileSync(xcodeEnvPath, 'utf8') : '';
      if (!xcodeEnv.includes('HERMES_CLI_PATH')) {
        fs.writeFileSync(xcodeEnvPath, xcodeEnv + exportLine);
      }
      return config;
    },
  ]);
}

function withNoUpgradeNag(config) {
  return withXcodeProject(config, (config) => {
    const project = config.modResults;
    const section = project.hash.project.objects.PBXProject;
    for (const key of Object.keys(section)) {
      const entry = section[key];
      if (entry && typeof entry === 'object' && entry.attributes) {
        entry.attributes.LastUpgradeCheck = 9999;
      }
    }

    // App-target-only tweaks (identified by the bundle id — project-level
    // configs don't carry one). The app keeps its own warnings; these only
    // silence noise coming from third-party framework headers and Pods
    // xcconfig both linking -lc++.
    const configs = project.hash.project.objects.XCBuildConfiguration;
    for (const key of Object.keys(configs)) {
      const entry = configs[key];
      const settings = entry && typeof entry === 'object' && entry.buildSettings;
      if (!settings || !settings.PRODUCT_BUNDLE_IDENTIFIER) continue;

      // "Ignoring duplicate libraries: '-lc++'" (target + Pods both add it)
      let ldflags = settings.OTHER_LDFLAGS || ['"$(inherited)"'];
      if (!Array.isArray(ldflags)) ldflags = [ldflags];
      if (!ldflags.some((f) => String(f).includes('no_warn_duplicate_libraries'))) {
        ldflags.push('"-Wl,-no_warn_duplicate_libraries"');
      }
      settings.OTHER_LDFLAGS = ldflags;

      // Warnings from imported third-party headers (ExpoModulesCore,
      // RevenueCatUI-Swift.h, prebuilt React-Core) surface while compiling
      // the app's Swift; -Xcc -w silences the clang-import side only.
      const swiftFlags = settings.OTHER_SWIFT_FLAGS || '"$(inherited)"';
      if (!String(swiftFlags).includes('-Xcc -w')) {
        settings.OTHER_SWIFT_FLAGS = String(swiftFlags).replace(/"$/, ' -Xcc -w"');
      }
    }
    return config;
  });
}

module.exports = function withCleanXcodeBuild(config) {
  return withNoUpgradeNag(withQuietPods(config));
};
