// Every user-facing legal string in one file. Before this existed the
// disclaimer was hand-written at three call sites and had already drifted into
// two different wordings. On a product that describes contracts for people who
// are not lawyers, that drift is the whole risk, so: import from here, never
// retype.
//
// Three claims travel together and none of them is optional:
//   1. AI reads the document (disclosed, not hidden behind the mascot)
//   2. it is not legal advice
//   3. no attorney-client relationship, no attorney-client privilege
//
// (1) is deliberate. The owner reversed the original "never say AI" rule on
// 2026-07-29: on a legally sensitive product, telling people how it works
// beats sounding magical.
//
// HOW "together" is satisfied, decided 2026-08-09 (audit finding 12). For ten
// days the analysis surfaces shipped claims 1 and 2 and left claim 3 sitting
// in a constant that nothing rendered, so this file's own rule was being
// violated on the one screen where it matters most. Putting all three in the
// footer turns a one-line note into a paragraph on three screens, and a
// disclaimer nobody finishes reading is worse than a short one. So: 1 and 2
// inline, 3 exactly one tap away, and the tap is not optional either. Render
// the analysis footer through `components/DisclaimerNote`, never a bare
// `<Text>{DISCLAIMER}</Text>` — the component is what guarantees the link is
// there. Surfaces that explain the product at length (onboarding, About These
// Summaries, support, Terms) keep all three inline, because there is room.

// Rides on every analysis surface: the review screen and the contract detail.
// Claims 1 and 2. DisclaimerNote appends the link that carries claim 3.
export const DISCLAIMER =
  'Contry uses AI to explain what your contract says. This is not legal advice.';

// The chat variant, phrased for a question-and-answer surface where the user
// is actively asking Contry things. Same two claims, same link after it.
export const DISCLAIMER_CHAT =
  'Contry uses AI to answer from your document. This is not legal advice.';

// The tappable half of the analysis footer. Deliberately says what is on the
// other side rather than "Learn more", so tapping is a choice about the legal
// limits and not a mystery link.
export const DISCLAIMER_MORE = 'What this is not.';

// The sentence that has to appear wherever the product is explained at length:
// onboarding, About These Summaries, Terms, and the store listing. Kept
// separate from DISCLAIMER because it is too long for an inline footer but too
// important to leave to the Terms alone.
export const NO_ATTORNEY_RELATIONSHIP =
  'Using Contraya does not create an attorney-client relationship, and nothing you put here is protected by attorney-client privilege.';

// Approved positioning. Owner's call on 2026-07-29, made against the advice
// that a credential claim naming no jurisdiction of licensure is treated as
// attorney advertising by several bars. Flagged for the pre-launch attorney
// review. Do not add a name, a firm, or a jurisdiction without that review,
// and do not use it anywhere near an analysis result, where it would push a
// reader toward hearing advice.
export const BUILT_BY = 'Built by lawyers, for everyday people.';

// The long-form version, used by About These Summaries and mirrored in Terms.
export const ABOUT_SUMMARIES_PARAGRAPHS = [
  'Contraya uses AI to read the documents you upload and describe what they say: the dates, the payments, the obligations, and the clauses people often want to know about. Everything you see comes from your own document, rewritten in everyday words.',
  'Contraya was built by lawyers, for everyday people. That is why it explains rather than advises, and it does not change what follows.',
  'Contraya is not a law firm and does not give legal advice. Using it does not create an attorney-client relationship, and nothing you put here is protected by attorney-client privilege. The summaries do not tell you what you should do, whether a contract is good for you, or whether a clause is enforceable where you live. Laws vary by state and country, and only a licensed attorney who knows your situation can advise you.',
  'Because the summaries are generated by AI, they can be wrong. AI can misread a date, miss a clause, or describe something with more confidence than it deserves. Always check the details against your document before relying on them, and keep the original. It is the only version that counts.',
  'If a contract involves a lot of money, your home, your health, or anything you cannot afford to get wrong, have a licensed attorney look at it.',
];
